export enum Configuration {
  PORT='PORT',
  HOST='DB_HOST',
  USERNAME='DB_USERNAME',
  PASSWORD='DB_PASSWORD',
  DATABASE='DB_DATABASE',
  DB_PORT='DB_PORT',
  JWT_SECRET='JWT_SECRET',

  MAIL_HOST='MAIL_HOST',
  MAIL_PORT='MAIL_PORT',
  MAIL_USUARIO='MAIL_USUARIO',
  MAIL_PASSWORD='MAIL_PASSWORD'
}